### ISSUE TITLE
App crashes while click on "SIGN IN USING VIRTUAL VIEWS" 

### ISSUE THREAD

**Issue by 1priyank1** [googlesamples/android-AutofillFramework#1]
```
                                                                                      --------- beginning of crash
03-27 17:42:13.203 17475-17475/com.example.android.autofillframework E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                       Process: com.example.android.autofillframework, PID: 17475
                                                                                       java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.android.autofillframework/com.example.android.autofillframework.app.VirtualLoginActivity}: android.view.InflateException: Binary XML file line #22: Binary XML file line #22: Error inflating class com.example.android.autofillframework.app.CustomVirtualView
                                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2758)
                                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2817)
                                                                                           at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1549)
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                           at android.os.Looper.loop(Looper.java:156)
                                                                                           at android.app.ActivityThread.main(ActivityThread.java:6440)
                                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                                           at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:746)
                                                                                        Caused by: android.view.InflateException: Binary XML file line #22: Binary XML file line #22: Error inflating class com.example.android.autofillframework.app.CustomVirtualView
                                                                                        Caused by: android.view.InflateException: Binary XML file line #22: Error inflating class com.example.android.autofillframework.app.CustomVirtualView
                                                                                        Caused by: java.lang.reflect.InvocationTargetException
                                                                                           at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                                           at java.lang.reflect.Constructor.newInstance(Constructor.java:333)
                                                                                           at android.view.LayoutInflater.createView(LayoutInflater.java:645)
                                                                                           at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
                                                                                           at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
                                                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:860)
                                                                                           at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
                                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
                                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
                                                                                           at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:412)
                                                                                           at android.app.Activity.setContentView(Activity.java:2492)
                                                                                           at com.example.android.autofillframework.app.VirtualLoginActivity.onCreate(VirtualLoginActivity.java:41)
                                                                                           at android.app.Activity.performCreate(Activity.java:6773)
                                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1195)
                                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2711)
                                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2817)
                                                                                           at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1549)
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                           at android.os.Looper.loop(Looper.java:156)
                                                                                           at android.app.ActivityThread.main(ActivityThread.java:6440)
                                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                                           at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:746)
                                                                                        Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/view/autofill/AutoFillManager;
                                                                                           at com.example.android.autofillframework.app.CustomVirtualView.<init>(CustomVirtualView.java:72)
                                                                                           at java.lang.reflect.Constructor.newInstance0(Native Method) 
                                                                                           at java.lang.reflect.Constructor.newInstance(Constructor.java:333) 
                                                                                           at android.view.LayoutInflater.createView(LayoutInflater.java:645) 
                                                                                           at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787) 
                                                                                           at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727) 
                                                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:860) 
                                                                                           at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821) 
                                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:518) 
                                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:426) 
                                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:377) 
                                                                                           at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:412) 
                                                                                           at android.app.Activity.setContentView(Activity.java:2492) 
                                                                                           at com.example.android.autofillframework.app.VirtualLoginActivity.onCreate(VirtualLoginActivity.java:41) 
                                                                                           at android.app.Activity.performCreate(Activity.java:6773) 
                                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1195) 
                                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2711) 
                                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2817) 
                                                                                           at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1549) 
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                           at android.os.Looper.loop(Looper.java:156) 
                                                                                           at android.app.ActivityThread.main(ActivityThread.java:6440) 
                                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                                           at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:746) 
                                                                                        Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.autofill.AutoFillManager" on path: DexPathList[[zip file "/data/app/com.example.android.autofillframework-XUA6dlToNwdNt-NCzDOMRg==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.android.autofillframework-XUA6dlToNwdNt-NCzDOMRg==/lib/x86, /system/lib, /system/vendor/lib]]
                                                                                           at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
                                                                                           at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                                           at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                           at com.example.android.autofillframework.app.CustomVirtualView.<init>(CustomVirtualView.java:72) 
                                                                                           at java.lang.reflect.Constructor.newInstance0(Native Method) 
                                                                                           at java.lang.reflect.Constructor.newInstance(Constructor.java:333) 
                                                                                           at android.view.LayoutInflater.createView(LayoutInflater.java:645) 
                                                                                           at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787) 
                                                                                           at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727) 
                                                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:860) 
                                                                                           at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821) 
                                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:518) 
                                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:426) 
                                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:377) 
                                                                                           at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:412) 
                                                                                           at android.app.Activity.setContentView(Activity.java:2492) 
                                                                                           at com.example.android.autofillframework.app.VirtualLoginActivity.onCreate(VirtualLoginActivity.java:41) 
                                                                                           at android.app.Activity.performCreate(Activity.java:6773) 
                                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1195) 
                                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2711) 
                                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2817) 
                                                                                           at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1549) 
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                           at android.os.Looper.loop(Looper.java:156) 
                                                                                           at android.app.ActivityThread.main(ActivityThread.java:6440) 
                                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                                           at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:746) 

```

**Comment by DougSig** [comment]
Thanks for reporting! Can you confirm you flashed a build from https://developer.android.com/preview/download.html on the device this occurred on?

**Comment by nitrohsu** [comment]
the same issue: can't find AutoFillManager
Using Emulator by Android O SystemImage x86 Google API. 
is the Latest Image for Emulator built based latest code?

**Comment by 1priyank1** [comment]
I have tested in emulator. Below are the details of Emulator:

Name: Pixel_API_O
CPU/ABI: Google APIs Intel Atom (x86)
Path: /home/priyank/.android/avd/Pixel_API_O.avd
Target: google_apis [Google APIs] (API level O)
Skin: pixel
SD Card: 100M
hw.dPad: no
runtime.network.speed: full
hw.accelerometer: yes
hw.device.name: pixel
vm.heapSize: 256
skin.dynamic: yes
hw.device.manufacturer: Google
image.androidVersion.codename: O
hw.gps: yes
hw.initialOrientation: Portrait
image.androidVersion.api: 25
hw.audioInput: yes
image.sysdir.1: system-images/android-O/google_apis/x86/
tag.id: google_apis
showDeviceFrame: yes
hw.camera.back: emulated
hw.mainKeys: no
AvdId: Pixel_API_O
hw.camera.front: emulated
hw.lcd.density: 480
avd.ini.displayname: Pixel API O
hw.gpu.mode: auto
hw.device.hash2: MD5:70f950b0b2b8960d1990af72fb74ad27
hw.ramSize: 1536
hw.trackBall: no
PlayStore.enabled: false
hw.battery: yes
hw.cpu.ncore: 2
hw.sdCard: yes
tag.display: Google APIs
runtime.network.latency: none
hw.keyboard: yes
hw.sensors.proximity: yes
disk.dataPartition.size: 800M
hw.sensors.orientation: yes
avd.ini.encoding: UTF-8
hw.gpu.enabled: yes

**Comment by DougSig** [comment]
Thanks. This is an emulator system image issue and we are working internally to fix it.

**Comment by DougSig** [comment]
This is fixed on the beta update released today.
