### ISSUE TITLE
Crash in AutofillService

### ISSUE THREAD

**Issue by commonsguy** [googlesamples/android-AutofillFramework#3]
```
05-23 14:31:51.368 22493-22493/com.example.android.autofillframework E/AndroidRuntime: FATAL EXCEPTION: main
   Process: com.example.android.autofillframework, PID: 22493
   java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.example.android.autofillframework.service.model.SavedAutofillValue.getTextValue()' on a null object reference
       at com.example.android.autofillframework.service.model.ClientFormData.applyToFields(ClientFormData.java:135)
       at com.example.android.autofillframework.service.AutofillHelper.newDataset(AutofillHelper.java:49)
       at com.example.android.autofillframework.service.AutofillHelper.newResponse(AutofillHelper.java:84)
       at com.example.android.autofillframework.service.MyAutofillService.onFillRequest(MyAutofillService.java:102)
       at android.service.autofill.AutofillService.lambda$-android_service_autofill_AutofillService_4873(AutofillService.java:139)
       at android.service.autofill.-$Lambda$svbjmB3NFhHnuZrn67G14PFSJlY.$m$0(Unknown Source:4)
       at android.service.autofill.-$Lambda$svbjmB3NFhHnuZrn67G14PFSJlY.executeMessage(Unknown Source:0)
       at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:37)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6535)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

You are not checking to see if `hintMap.get(hint)` returns `null`.

This is coming when I launch an activity with this layout:

```
<?xml version="1.0" encoding="utf-8"?>
<android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
  xmlns:app="http://schemas.android.com/apk/res-auto"
  xmlns:tools="http://schemas.android.com/tools"
  android:layout_width="match_parent"
  android:layout_height="match_parent"
  tools:context="com.commonsware.android.autofill.client.MainActivity">

  <EditText
    android:id="@+id/username"
    android:layout_width="0dp"
    android:layout_height="wrap_content"
    android:layout_marginLeft="8dp"
    android:layout_marginRight="8dp"
    android:layout_marginTop="8dp"
    android:autofillHints="username"
    android:ems="10"
    android:inputType="textPersonName"
    android:text="@string/hint_username"
    app:layout_constraintLeft_toLeftOf="parent"
    app:layout_constraintRight_toRightOf="parent"
    app:layout_constraintTop_toTopOf="parent" />

  <EditText
    android:id="@+id/passphrase"
    android:layout_width="0dp"
    android:layout_height="wrap_content"
    android:layout_marginLeft="8dp"
    android:layout_marginRight="8dp"
    android:layout_marginTop="8dp"
    android:autofillHints="password"
    android:ems="10"
    android:hint="@string/hint_passphrase"
    android:inputType="textPassword"
    app:layout_constraintHorizontal_bias="0.0"
    app:layout_constraintLeft_toLeftOf="parent"
    app:layout_constraintRight_toRightOf="parent"
    app:layout_constraintTop_toBottomOf="@id/username" />

  <EditText
    android:id="@+id/cc"
    android:layout_width="0dp"
    android:layout_height="wrap_content"
    android:layout_marginLeft="8dp"
    android:layout_marginRight="8dp"
    android:layout_marginTop="8dp"
    android:autofillHints="creditCardNumber"
    android:ems="10"
    android:inputType="textPersonName"
    android:text="@string/hint_credit_card_number"
    app:layout_constraintLeft_toLeftOf="parent"
    app:layout_constraintRight_toRightOf="parent"
    app:layout_constraintTop_toBottomOf="@id/passphrase" />

  <Button
    android:id="@+id/save"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:layout_marginEnd="8dp"
    android:layout_marginRight="8dp"
    android:layout_marginTop="8dp"
    android:text="@string/btn_save"
    app:layout_constraintRight_toRightOf="parent"
    app:layout_constraintTop_toBottomOf="@id/cc" />
</android.support.constraint.ConstraintLayout>
```

**Comment by DougSig** [comment]
Thanks for reporting. When you get a chance can you try it on the latest version that just got pushed?

**Comment by commonsguy** [comment]
I get build errors. After downgrading to production releases of Gradle (3.3) and the Android Plugin for Gradle (2.3.2), I get:

```
:Application:mergeDebugResources
[string/app_name] /tmp/android-AutofillFramework/Application/src/main/res/values/strings.xml    [string/app_name] /tmp/android-AutofillFramework/Application/src/main/res/values/base-strings.xml: Error: Duplicate resources
:Application:mergeDebugResources FAILED
```

And I can confirm that `app_name` is defined in the two locations specified.

**Comment by DougSig** [comment]
template-dimens.xml and template-styles.xml should have been removed on this latest push, I'm investigating why they weren't. If you still want to help troubleshoot, you can remove those files and try again.

**Comment by commonsguy** [comment]
Those files weren't the problem. I assume it was `base-strings.xml`.

Your `Application/` code depends upon Gson, but does not have that listed in dependencies. Even after I add it, I get Gson-related compile errors:

```
/tmp/android-AutofillFramework/Application/src/main/java/com/example/android/autofillframework/service/datasource/LocalAutofillRepository.java:68: error: cannot find symbol
                        .fromJson(new JSONObject(clientFormDataString));
                        ^
  symbol:   method fromJson(JSONObject)
  location: class ClientFormData
/tmp/android-AutofillFramework/Application/src/main/java/com/example/android/autofillframework/service/datasource/LocalAutofillRepository.java:94: error: cannot find symbol
        allAutofillData.add(clientFormData.toJson().toString());
                                          ^
  symbol:   method toJson()
  location: variable clientFormData of type ClientFormData
```

**Comment by DougSig** [comment]
We had issues with our publishing script but it's mostly resolved now. Thanks for your patience!

**Comment by commonsguy** [comment]
This time it builds (again, after dropping back to Gradle 3.3 and Android Plugin for Gradle 2.3.2), and this issue seems to be resolved.

Thanks!
