### ISSUE TITLE
Enable Authenticate response app crash 

### ISSUE THREAD

**Issue by nikz-dev** [googlesamples/android-AutofillFramework#6]
```
com.example.android.autofillframework E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                       Process: com.example.android.autofillframework, PID: 20182
                                                                                       java.lang.IllegalArgumentException: ids cannot be null or empry
                                                                                           at android.service.autofill.FillResponse$Builder.setAuthentication(FillResponse.java:272)
                                                                                           at com.example.android.autofillframework.multidatasetservice.MyAutofillService.onFillRequest(MyAutofillService.java:80)
                                                                                           at android.service.autofill.AutofillService.lambda$-android_service_autofill_AutofillService_4040(AutofillService.java:119)
                                                                                           at android.service.autofill.-$Lambda$svbjmB3NFhHnuZrn67G14PFSJlY.$m$0(Unknown Source:4)
                                                                                           at android.service.autofill.-$Lambda$svbjmB3NFhHnuZrn67G14PFSJlY.executeMessage(Unknown Source:0)
                                                                                           at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:37)
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                                           at android.os.Looper.loop(Looper.java:164)
                                                                                           at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                                           at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

Second issue is Credit card autofilling also not working.

**Comment by DougSig** [comment]
Can you confirm that you're syncd with the latest repo? I cannot reproduce this.

**Comment by DougSig** [comment]
Sync with the latest and you should not have this problem (the compile errors were occuring in the **service** package which should have been deleted ( #5 ).
